import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { detectImportAlias } from "./detect.ts";
import { fileExtension, formatIcon } from "./format.ts";
import type { Framework, IconRecord } from "./types.ts";
import { toKebabCase, toPascalCase } from "./utils.ts";

export type WrittenIcon = {
  iconId: string;
  componentName: string;
  filePath: string;
  alreadyExists: boolean;
  importStatement: string;
};

function fileNameFor(name: string, framework: Framework): string {
  return `${toKebabCase(name)}.${fileExtension(framework)}`;
}

function ensureBarrel(
  outDirAbs: string,
  framework: Framework,
  exportName: string,
  fileBase: string,
): void {
  if (framework === "flutter" || framework === "svg") return;
  const barrel = join(outDirAbs, "index.ts");
  const specifier =
    framework === "vue"
      ? `./${fileBase}.vue`
      : framework === "svelte"
        ? `./${fileBase}.svelte`
        : `./${fileBase}`;
  const line =
    framework === "vue" || framework === "svelte"
      ? `export { default as ${exportName} } from "${specifier}";\n`
      : `export { ${exportName} } from "${specifier}";\n`;
  let existing = "";
  if (existsSync(barrel)) existing = readFileSync(barrel, "utf-8");
  if (existing.includes(`from "${specifier}"`)) return;
  if (!existing.startsWith("// Generated by aria-icons")) {
    existing = `// Generated by aria-icons — safe to commit\n${existing}`;
  }
  writeFileSync(barrel, `${existing.trimEnd()}\n${line}`, "utf-8");
}

export function writeIconFile(options: {
  cwd: string;
  outDir: string;
  framework: Framework;
  icon: IconRecord;
  force?: boolean;
}): WrittenIcon {
  const { cwd, outDir, framework, icon, force } = options;
  const componentName = toPascalCase(icon.name) || "Icon";
  const fileBase = toKebabCase(icon.name);
  const filePath = join(cwd, outDir, fileNameFor(icon.name, framework));
  const alreadyExists = existsSync(filePath);

  mkdirSync(dirname(filePath), { recursive: true });
  if (!alreadyExists || force) {
    const code = formatIcon(icon.svg, icon.name, framework, icon.id);
    writeFileSync(filePath, code.endsWith("\n") ? code : `${code}\n`, "utf-8");
  }

  ensureBarrel(join(cwd, outDir), framework, componentName, fileBase);

  const alias = detectImportAlias(cwd, outDir);
  const importStatement = `import { ${componentName} } from "${alias}"`;

  return {
    iconId: icon.id,
    componentName,
    filePath: relative(cwd, filePath),
    alreadyExists,
    importStatement,
  };
}
