import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeIconFile } from "./write.ts";

const icon = {
  id: "lucide:arrow-up",
  legacyId: "lucide-icons-arrow-up",
  set: "lucide-icons",
  name: "arrow-up",
  styleId: "line",
  svg: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M1 1" /></svg>',
};

describe("writeIconFile barrel", () => {
  test("exports arrow-up even when arrow-up-right already exists", () => {
    const cwd = mkdtempSync(join(tmpdir(), "aria-icons-"));
    const outDir = "src/components/icons";
    mkdirSync(join(cwd, outDir), { recursive: true });
    writeFileSync(
      join(cwd, outDir, "index.ts"),
      `// Generated by aria-icons — safe to commit\nexport { ArrowUpRight } from "./arrow-up-right";\n`,
      "utf-8",
    );
    writeIconFile({ cwd, outDir, framework: "react", icon });
    const barrel = readFileSync(join(cwd, outDir, "index.ts"), "utf-8");
    expect(barrel).toContain('from "./arrow-up-right"');
    expect(barrel).toContain('from "./arrow-up"');
  });

  test("force overwrites an existing file", () => {
    const cwd = mkdtempSync(join(tmpdir(), "aria-icons-"));
    const outDir = "src/components/icons";
    writeIconFile({ cwd, outDir, framework: "react", icon });
    writeIconFile({
      cwd,
      outDir,
      framework: "react",
      icon: { ...icon, svg: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M2 2" /></svg>' },
      force: true,
    });
    const body = readFileSync(join(cwd, outDir, "arrow-up.tsx"), "utf-8");
    expect(body).toContain("M2 2");
  });
});
