export type ChangelogEntry = {
	date: string;
	version: string;
	title: string;
	tag: string;
	summary: string;
	removed?: string[];
	added?: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
	{
		date: "2026-10-03",
		version: "1M",
		title: "One million icons",
		tag: "Milestone",
		summary:
			"Aria Icons has passed one million icons. The browse catalog now lists 1,000,149 icons across 552 sets, after vendoring 68 more open families: the Material Symbols weights from Thin 100 to Bold 700, LibreOffice's icon themes, app icons from Godot, KiCad, Krita, QGIS, FreeCAD, and IntelliJ, plus design systems from SAP, Red Hat, IBM Carbon, and Pinterest Gestalt. A new quality pass repaired markup across every vendored pack and dropped broken and duplicate icons. Families that were too small, or were avatar art rather than icons, were removed.",
		added: [
			"Added Adwaita++ Icons in Color and Symbolic (6,943 icons).",
			"Added Aksel Icons (959 icons).",
			"Added Analog Gothic (34 icons).",
			"Added Atom Material Icons (3,827 icons).",
			"Added Auro Icons (82 icons).",
			"Added Bearded Icons (389 icons).",
			"Added Charmed Icons (249 icons).",
			"Added Chess Art (18 icons).",
			"Added City Icons (309 icons).",
			"Added Databricks Architecture Icons in Color, Mono, Outline, and Tile (284 icons).",
			"Added Dev Hearts (32 icons).",
			"Added Evolvere Icons in Color and Symbolic (1,733 icons).",
			"Added FreeCAD Icons (1,604 icons).",
			"Added Frog Emojis (172 icons).",
			"Added Gestalt Icons (409 icons).",
			"Added Godot Editor Icons (1,124 icons).",
			"Added Great Icons (197 icons).",
			"Added Gruvbox Plus Icons in Color and Symbolic (12,238 icons).",
			"Added Halo Icons in Color and Symbolic (3,191 icons).",
			"Added Hatter Icons in Color and Symbolic (1,158 icons).",
			"Added IBM Carbon Pictograms (1,576 icons).",
			"Added Icomo (417 icons).",
			"Added IntelliJ Platform Icons in Classic and New UI (3,110 icons).",
			"Added Josemi Icons (911 icons).",
			"Added KiCad Icons (698 icons).",
			"Added Krita Icons (892 icons).",
			"Added LibreOffice Breeze (3,968 icons).",
			"Added LibreOffice Colibre (4,760 icons).",
			"Added LibreOffice Elementary (4,181 icons).",
			"Added LibreOffice Karasa Jaga (4,730 icons).",
			"Added LibreOffice Sifr (4,134 icons).",
			"Added LibreOffice Sukapura (4,467 icons).",
			"Added LibreOffice Yaru (3,314 icons).",
			"Added Lila HD Icons in Color and Symbolic (3,154 icons).",
			"Added Mapillary Traffic Signs (1,581 icons).",
			"Added Masalla Icons in Color and Symbolic (1,910 icons).",
			"Added Material Product Icons (333 icons).",
			"Added Material Symbols Bold 700 in Outlined, Outlined Filled, Rounded, Rounded Filled, Sharp, and Sharp Filled (19,966 icons).",
			"Added Material Symbols Light 300 in Outlined, Outlined Filled, Rounded, Rounded Filled, Sharp, and Sharp Filled (19,983 icons).",
			"Added Material Symbols Medium 500 in Outlined, Outlined Filled, Rounded, Rounded Filled, Sharp, and Sharp Filled (19,992 icons).",
			"Added Material Symbols SemiBold 600 in Outlined, Outlined Filled, Rounded, Rounded Filled, Sharp, and Sharp Filled (19,992 icons).",
			"Added Material Symbols Thin 100 in Outlined, Outlined Filled, Rounded, Rounded Filled, Sharp, and Sharp Filled (19,931 icons).",
			"Added Moda Operandi Icons (154 icons).",
			"Added Mulberry Symbols (3,433 icons).",
			"Added Neo Candy Icons in Color and Symbolic (3,152 icons).",
			"Added Nordzy Icons in Color and Symbolic (3,871 icons).",
			"Added NPS Map Symbols (865 icons).",
			"Added Obsidian Icons in Color and Symbolic (3,401 icons).",
			"Added Open Crop Icons (247 icons).",
			"Added OpenMoji Black (2,123 icons).",
			"Added Orange Accessibility Icons (14 icons).",
			"Added OSM Carto Symbols (310 icons).",
			"Added PUXL Icons (302 icons).",
			"Added QGIS Icons (1,332 icons).",
			"Added Red Hat Icons (1,224 icons).",
			"Added SAP Horizon Icons (693 icons).",
			"Added SAP Icons (693 icons).",
			"Added Scholar Icons (108 icons).",
			"Added Serendie Symbols in Filled and Outlined (610 icons).",
			"Added Simple Icons (VS Code) in Minimalistic and Simple (403 icons).",
			"Added Soaring Symbols in Icon, Icon Mono, Logo, Logo Mono, and Tail (225 icons).",
			"Added Sparkle Icons in Black, Colored, and Light (36 icons).",
			"Added Spectrum 2 Icons (67 icons).",
			"Added Suru Icons in Color and Symbolic (210 icons).",
			"Added Suru++ Ubuntu in Color and Symbolic (3,551 icons).",
			"Added Symbols (VS Code) (368 icons).",
			"Added Thermal Comfort Icons (15 icons).",
			"Added Yaru++ Icons in Color and Symbolic (4,510 icons).",
		],
		removed: [
			"Removed 3dicons, which shipped blurred renders of its 3D artwork.",
			"Removed the avatar packs Avataaars, Big Heads, and Multiavatar.",
			"Removed Quill Icons, MorphNext, and Uber Base Web Icons.",
			"Removed Bili Icon Pack, Discord Badge Vault, and HA Akentner Icons, which had fewer than five icons left after the quality pass.",
		],
	},
	{
		date: "2026-10-02",
		version: "943k",
		title: "47 more icon families",
		tag: "Icons",
		summary:
			"Vendored 47 more open icon families, including Bubbles, Heroicons v1, Papirus, Zafiro, Mint, and a wave of Breeze and macOS-style desktop themes. The browse catalog now lists 943,000 icons across 494 sets, and production builds give the catalog generator enough memory to index all of them.",
		added: [
			"Added BigSur Elegant in Color and Symbolic (3,142 icons).",
			"Added BigSur Icon Theme in Color and Symbolic (6,179 icons).",
			"Added Breeze Blue in Color and Symbolic (3,996 icons).",
			"Added Breeze Blur in Color and Symbolic (3,664 icons).",
			"Added Breeze Chameleon in Color and Symbolic (6,652 icons).",
			"Added Breeze Noir in Color and Symbolic (5,125 icons).",
			"Added Breeze openSUSE in Color and Symbolic (5,168 icons).",
			"Added Breeze Phoenix in Color and Symbolic (3,920 icons).",
			"Added Breeze Shamrock in Color and Symbolic (3,638 icons).",
			"Added Breeze Splendent in Color and Symbolic (3,636 icons).",
			"Added Bubble Icon Theme in Color and Symbolic (3,671 icons).",
			"Added Bubbles in Outline and Solid (412 icons).",
			"Added Colloid Icon Theme in Color and Symbolic (6,722 icons).",
			"Added Color Flow Icons in Color and Symbolic (9,218 icons).",
			"Added Elementary KDE Icons in Color and Symbolic (13,892 icons).",
			"Added Emerald Icon Theme in Color and Symbolic (9,421 icons).",
			"Added Fantasy Icon Theme in Color and Symbolic (3,403 icons).",
			"Added Flatery in Color and Symbolic (5,067 icons).",
			"Added Glory Icon Theme in Color and Symbolic (3,221 icons).",
			"Added Heroicons v1 in Outline and Solid (460 icons).",
			"Added Inkscape Open Symbols (1,383 icons).",
			"Added Inverse Icon Theme in Color and Symbolic (3,879 icons).",
			"Added Ketsa Icon Theme in Color and Symbolic (1,698 icons).",
			"Added Komps Icon Theme in Color and Symbolic (853 icons).",
			"Added Lyra Icon Theme in Color and Symbolic (3,213 icons).",
			"Added MacTahoe Icon Theme in Color and Symbolic (7,023 icons).",
			"Added MATE Icon Theme in Color and Symbolic (983 icons).",
			"Added McMuse Icon Theme in Color and Symbolic (3,225 icons).",
			"Added Mint L Icons in Color and Symbolic (1,256 icons).",
			"Added Mint X Icons in Color and Symbolic (2,544 icons).",
			"Added Mint Y Icons in Color and Symbolic (1,269 icons).",
			"Added Miya Icon Theme in Color and Symbolic (3,225 icons).",
			"Added Newaita in Color and Symbolic (5,891 icons).",
			"Added Newaita Reborn in Color and Symbolic (4,290 icons).",
			"Added Numix Square (12,515 icons).",
			"Added Oranchelo Icon Theme in Color and Symbolic (4,629 icons).",
			"Added OS Catalina Icons in Color and Symbolic (9,359 icons).",
			"Added Oxygen Icons in Color and Symbolic (405 icons).",
			"Added Papirus Icon Theme in Color and Symbolic (18,502 icons).",
			"Added Reversal Icon Theme in Color and Symbolic (6,420 icons).",
			"Added Spectrum Color Icons in Color and Symbolic (6,286 icons).",
			"Added Tela Circle in Color and Symbolic (5,619 icons).",
			"Added UOS Icons in Color and Symbolic (9,000 icons).",
			"Added Vitamix (Decathlon) (492 icons).",
			"Added Win10Sur Icon Theme in Color and Symbolic (3,477 icons).",
			"Added Win11 Icon Theme in Color and Symbolic (5,925 icons).",
			"Added Zafiro Icons in Color and Symbolic (9,657 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "706k",
		title: "29 more icon families",
		tag: "Icons",
		summary:
			"Vendored 29 open icon families, including Linux desktop themes, science and cloud logos, and token marks. The browse catalog now lists 706,500 icons across 450 sets.",
		added: [
			"Added Arc Icon Theme in Color and Symbolic (1,429 icons).",
			"Added Avataaars (97 icons).",
			"Added Big Heads (70 icons).",
			"Added Bioicons (2,789 icons).",
			"Added Candy Icons in Color and Symbolic (3,587 icons).",
			"Added CNCF Artwork (2,565 icons).",
			"Added Cosmos Chain Registry (646 icons).",
			"Added Deepin Icon Theme in Color and Symbolic (4,508 icons).",
			"Added Elementary OS Icons in Color and Symbolic (1,130 icons).",
			"Added Faenza Icon Theme in Color and Symbolic (2,424 icons).",
			"Added Flat Remix Icons in Color and Symbolic (14,561 icons).",
			"Added Fluent Icon Theme in Color and Symbolic (6,378 icons).",
			"Added GNOME Adwaita in Color and Symbolic (789 icons).",
			"Added KDE Breeze Icons in Color and Symbolic (6,787 icons).",
			"Added Kora Icon Theme in Color and Symbolic (15,972 icons).",
			"Added McMojave Circle in Color and Symbolic (6,224 icons).",
			"Added Moka Icon Theme (831 icons).",
			"Added Multiavatar (16 icons).",
			"Added Numix Circle (12,521 icons).",
			"Added Paper Icon Theme in Color and Symbolic (2,567 icons).",
			"Added Qogir Icon Theme in Color and Symbolic (6,687 icons).",
			"Added Solana Token List (528 icons).",
			"Added Suru Plus in Color and Symbolic (18,965 icons).",
			"Added Tela Icon Theme in Color and Symbolic (5,529 icons).",
			"Added Ubuntu Yaru in Color and Symbolic (2,657 icons).",
			"Added Vimix Icon Theme in Color and Symbolic (4,654 icons).",
			"Added We10X Icon Theme in Color and Symbolic (5,966 icons).",
			"Added Web Awesome Icons in Fill, Jelly, and Utility (715 icons).",
			"Added WhiteSur Icon Theme in Color and Symbolic (6,621 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "567k",
		title: "23 more icon families",
		tag: "Icons",
		summary:
			"Vendored 23 open icon families, including file-type icons, brand and bank logos, Azure service icons, and design-system sets. The browse catalog now lists 566,800 icons across 420 sets.",
		added: [
			"Added Azure Icon Collection (1,114 icons).",
			"Added Badgen Icons (82 icons).",
			"Added Bank Logos (424 icons).",
			"Added Dripicons (200 icons).",
			"Added Elementor Icons (514 icons).",
			"Added File Icon Vectors in Classic, Vivid, Square O, and High Contrast (1,637 icons).",
			"Added IcoFont (2,095 icons).",
			"Added Icon Brew (310 icons).",
			"Added Instructure UI Icons in Line, Fill, and Custom (859 icons).",
			"Added JTB Icons (1,482 icons).",
			"Added Microns (172 icons).",
			"Added Nataicons (120 icons).",
			"Added Orchid Icons (283 icons).",
			"Added Pe-icon-7-stroke (202 icons).",
			"Added Power BI Icons (95 icons).",
			"Added Raivo Issuer Icons (1,164 icons).",
			"Added Sanity Icons (236 icons).",
			"Added Small-n-flat (169 icons).",
			"Added SVG Loaders (12 icons).",
			"Added Toe Icons (120 icons).",
			"Added VectorLogoZone (1,761 icons).",
			"Added Vitamix by Decathlon (492 icons).",
			"Added Zero Icons (369 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "553k",
		title: "12 more icon families",
		tag: "Icons",
		summary:
			"Vendored 12 open icon families, including desktop themes, map symbols, and weather sets. The browse catalog now lists 552,900 icons across 397 sets.",
		added: [
			"Added Firefox OS Icons (209 icons).",
			"Added Geomicons Open (58 icons).",
			"Added GovIcons (114 icons).",
			"Added Kamon (171 icons).",
			"Added La Capitaine Icon Theme (6,850 icons).",
			"Added Metro UI Icons (967 icons).",
			"Added Olicons in Outline, Fill, Sharp Outline, and Sharp Fill (678 icons).",
			"Added SJJB Map Icons (245 icons).",
			"Added Tango Icon Theme (215 icons).",
			"Added ThemeIsle Icons (100 icons).",
			"Added Weather Underground Icons in Color and Fill (80 icons).",
			"Added Zocial (113 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "543k",
		title: "120 new icon families",
		tag: "Icons",
		summary:
			"Vendored 120 open icon families that were not already in the library. The browse catalog now lists 543,100 icons across 385 sets.",
		added: [
			"Added 3dicons (8 icons).",
			"Added AWS Icons (1,001 icons).",
			"Added Aegis Icons (1,016 icons).",
			"Added AirQo Icons (1,384 icons).",
			"Added Altrex Icons (1,585 icons).",
			"Added AnimateIcons (1,140 icons).",
			"Added Appstract (590 icons).",
			"Added Arashi Icon Set (262 icons).",
			"Added Astroicons (53 icons).",
			"Added Azure Visio Stencils (1,236 icons).",
			"Added Bancos em SVG (130 icons).",
			"Added Basil Icons (500 icons).",
			"Added Bili Icon Pack (6 icons).",
			"Added Blobmoji (4,155 icons).",
			"Added Bootstrap Italia Icons (190 icons).",
			"Added Brightlayer UI Icons (4,754 icons).",
			"Added Buckaroo Payment Media (156 icons).",
			"Added Calcite UI Icons (3,504 icons).",
			"Added Catmoji (98 icons).",
			"Added Climacons (33 icons).",
			"Added Counter-Strike Icons (1,537 icons).",
			"Added Country Flags (255 icons).",
			"Added CryptoFont (88 icons).",
			"Added Cryptocoins (330 icons).",
			"Added Developer Icons (334 icons).",
			"Added Disarto Icons (1,504 icons).",
			"Added Discord Badge Vault (2 icons).",
			"Added Doodle Icons (439 icons).",
			"Added Duma Icons (451 icons).",
			"Added Duo Blazor Icons (91 icons).",
			"Added Emblemicons (1,064 icons).",
			"Added Erxes Icons (754 icons).",
			"Added Eyecons (460 icons).",
			"Added FamFamFam Silk (997 icons).",
			"Added File Icons (931 icons).",
			"Added Finmarks (304 icons).",
			"Added Flow Icons (8,100 icons).",
			"Added Forge Icon (568 icons).",
			"Added Frost Icon Theme (277 icons).",
			"Added Game Icon Pack (815 icons).",
			"Added Get It On Badges (13 icons).",
			"Added Global Bank Logos (93 icons).",
			"Added HA Akentner Icons (1 icon).",
			"Added HA Cupertino Icons (595 icons).",
			"Added HA Energy Node Icons (20 icons).",
			"Added HD Icons (603 icons).",
			"Added HV UI Kit Icons (521 icons).",
			"Added HashiCorp Flight (1,352 icons).",
			"Added Helldivers 2 Stratagems (109 icons).",
			"Added Hyperliquid Coin SVGs (223 icons).",
			"Added Iconoteka (14,970 icons).",
			"Added Iconsans (664 icons).",
			"Added Iconspeck (672 icons).",
			"Added Icoziv (1,746 icons).",
			"Added Idea Icon Pack (71 icons).",
			"Added Illustration Foundry (784 icons).",
			"Added Jedd Icons (383 icons).",
			"Added JetBrains Icons (767 icons).",
			"Added JustVector Icons (151 icons).",
			"Added KDesign Icons (2,017 icons).",
			"Added Kendo SVG Icons (2,481 icons).",
			"Added Kivex (309 icons).",
			"Added Koobiq Icons (1,088 icons).",
			"Added Lawnicons (10,171 icons).",
			"Added LibreICONS (2,439 icons).",
			"Added Line MD (1,222 icons).",
			"Added Linea Iconset (1,431 icons).",
			"Added Linearicons (170 icons).",
			"Added LivelyIcons (1,319 icons).",
			"Added Lovelace Weather Icons (15 icons).",
			"Added MOBAIcons (475 icons).",
			"Added MS Emoji (7,906 icons).",
			"Added MSR Icons (2,137 icons).",
			"Added Material OS Icon Pack (31 icons).",
			"Added Monster Hunter Icons (353 icons).",
			"Added MorphNext (2 icons).",
			"Added Moving Icons (549 icons).",
			"Added NSW Design System Icons (15 icons).",
			"Added Neu Icons (1,508 icons).",
			"Added Next Icons (353 icons).",
			"Added Ontario Design System Icons (137 icons).",
			"Added OpenTiny Icons (709 icons).",
			"Added Oracle Font APEX (2,320 icons).",
			"Added Orange Icons (750 icons).",
			"Added Orangeclock Icons (15 icons).",
			"Added Orbit Icons (358 icons).",
			"Added Papirus Icons (2,219 icons).",
			"Added Payment Methods SVG (35 icons).",
			"Added PaymentFont (116 icons).",
			"Added Pixel Vault (69 icons).",
			"Added ProXIcons (1,634 icons).",
			"Added Proxy App Icon Set (83 icons).",
			"Added PureIconPack (morirain) (15 icons).",
			"Added Quill Icons (1 icon).",
			"Added React Crypto Icons (1,200 icons).",
			"Added React Pay Icons (596 icons).",
			"Added React Suite Icons (277 icons).",
			"Added Rpg Awesome (495 icons).",
			"Added Rune Icons (2,895 icons).",
			"Added SWM Icon Pack (894 icons).",
			"Added Samsung One UI Icons (883 icons).",
			"Added Semantic UI Icons (2,228 icons).",
			"Added ShopIcons (996 icons).",
			"Added Sketch Icons (671 icons).",
			"Added Sketchybar App Font (674 icons).",
			"Added Slate Free SVG Icons (10 icons).",
			"Added Suomi.fi Icons (242 icons).",
			"Added Tech Stack Icon (1,386 icons).",
			"Added Terrane (972 icons).",
			"Added TinyGlyphs (250 icons).",
			"Added Twilio Paste Icons (338 icons).",
			"Added Uber Base Web Icons (33 icons).",
			"Added VK Icons (3,531 icons).",
			"Added VS Code Iconset (114 icons).",
			"Added VS Code Material Icon Theme (910 icons).",
			"Added Vigil Icons (111 icons).",
			"Added doo-iconik (595 icons).",
			"Added selfh.st Icons (7,273 icons).",
			"Added taurbalaur SVG Icons (15 icons).",
			"Added vscode-icons (1,665 icons).",
		],
	},
	{
		date: "2026-08-18",
		version: "morph",
		title: "Icon morph playground",
		tag: "Product",
		summary:
			"Stroke icons can now morph into each other in the inspector, powered by [morphicons](https://www.morphicons.com/). Optimal rotation is solved in closed form; springs stay interruptible.",
		added: [
			"Added a Morph tab beside Static: pick two or more line icons, play the sequence, and scrub the interpolation.",
			"Added drag-to-reorder on the morph sequence, plus copy/export for React, Vue, Svelte, React Native, HTML, and vanilla.",
			"Added morph compatibility — path structure, geometry, stroke, and interpolation.",
		],
	},
	{
		date: "2026-08-13",
		version: "dual-era",
		title: "Cursor MCP compatibility",
		tag: "MCP",
		summary:
			"The remote MCP endpoint now speaks both the stateless `2026-07-28` protocol and the handshake-based protocol Cursor still uses. No session stickiness — `initialize` is answered in-request and then forgotten.",
		added: [
			"Added dual-era Streamable HTTP: Cursor `initialize` / `tools/list` / `tools/call` work without the new MCP headers.",
			"Added `ping` and `notifications/initialized` handling for handshake clients.",
			"Kept `server/discover` and per-request `_meta` validation for `2026-07-28` clients.",
		],
	},
	{
		date: "2026-08-09",
		version: "2026-07-28",
		title: "Stateless MCP architecture",
		tag: "MCP",
		summary:
			"Migrated the remote MCP server to protocol `2026-07-28`. Every request is now self-contained — no sessions, no handshake, ready for serverless deployment.",
		removed: [
			"Removed the `initialize` / `initialized` handshake in favor of per-request metadata.",
			"Removed `Mcp-Session-Id` and all session stickiness from the Streamable HTTP transport.",
			"Removed the GET SSE stream endpoint (deprecated HTTP+SSE transport).",
			"Removed the `@modelcontextprotocol/sdk` dependency and duplicated handler code.",
			"Dropped support for legacy protocol version `2024-11-05`.",
		],
		added: [
			"Added `server/discover` to advertise supported versions, capabilities, and server identity.",
			"Added per-request validation of `params._meta.io.modelcontextprotocol/protocolVersion`.",
			"Added required HTTP headers: `MCP-Protocol-Version`, `Mcp-Method`, and `Mcp-Name`.",
			"Added `resultType: \"complete\"` on all JSON-RPC results.",
			"Added `io.modelcontextprotocol/serverInfo` in `_meta` on every response.",
			"Added cache hints (`ttlMs` + `cacheScope: \"public\"`) on discover, list, and read operations.",
			"Added spec error codes `-32020` (HeaderMismatch), `-32022` (UnsupportedProtocolVersion), and `-32601` (Method not found).",
		],
	},
	{
		date: "2025-12-13",
		version: "2024-11-05",
		title: "Initial MCP server",
		tag: "MCP",
		summary:
			"Shipped the first remote MCP endpoint for Aria Icons with tools and resources over Streamable HTTP using the legacy session-based protocol.",
		added: [
			"Added `POST /api/mcp` as a JSON-RPC endpoint for remote MCP clients.",
			"Added the `initialize` / `initialized` session handshake.",
			"Added tools: `list_icons` and `get_icon_svg`.",
			"Added resources for each icon set and a combined `all` resource.",
			"Added the MCP connect dialog in the UI.",
		],
	},
];
