export type ChangelogEntry = {
	date: string;
	version: string;
	title: string;
	tag: string;
	summary: string;
	removed?: string[];
	added?: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
	{
		date: "2026-10-02",
		version: "706k",
		title: "29 more icon families",
		tag: "Icons",
		summary:
			"Vendored 29 open icon families, including Linux desktop themes, science and cloud logos, and token marks. The browse catalog now lists 706,500 icons across 450 sets.",
		added: [
			"Added Arc Icon Theme in Color and Symbolic (1,429 icons).",
			"Added Avataaars (97 icons).",
			"Added Big Heads (70 icons).",
			"Added Bioicons (2,789 icons).",
			"Added Candy Icons in Color and Symbolic (3,587 icons).",
			"Added CNCF Artwork (2,565 icons).",
			"Added Cosmos Chain Registry (646 icons).",
			"Added Deepin Icon Theme in Color and Symbolic (4,508 icons).",
			"Added Elementary OS Icons in Color and Symbolic (1,130 icons).",
			"Added Faenza Icon Theme in Color and Symbolic (2,424 icons).",
			"Added Flat Remix Icons in Color and Symbolic (14,561 icons).",
			"Added Fluent Icon Theme in Color and Symbolic (6,378 icons).",
			"Added GNOME Adwaita in Color and Symbolic (789 icons).",
			"Added KDE Breeze Icons in Color and Symbolic (6,787 icons).",
			"Added Kora Icon Theme in Color and Symbolic (15,972 icons).",
			"Added McMojave Circle in Color and Symbolic (6,224 icons).",
			"Added Moka Icon Theme (831 icons).",
			"Added Multiavatar (16 icons).",
			"Added Numix Circle (12,521 icons).",
			"Added Paper Icon Theme in Color and Symbolic (2,567 icons).",
			"Added Qogir Icon Theme in Color and Symbolic (6,687 icons).",
			"Added Solana Token List (528 icons).",
			"Added Suru Plus in Color and Symbolic (18,965 icons).",
			"Added Tela Icon Theme in Color and Symbolic (5,529 icons).",
			"Added Ubuntu Yaru in Color and Symbolic (2,657 icons).",
			"Added Vimix Icon Theme in Color and Symbolic (4,654 icons).",
			"Added We10X Icon Theme in Color and Symbolic (5,966 icons).",
			"Added Web Awesome Icons in Fill, Jelly, and Utility (715 icons).",
			"Added WhiteSur Icon Theme in Color and Symbolic (6,621 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "567k",
		title: "23 more icon families",
		tag: "Icons",
		summary:
			"Vendored 23 open icon families, including file-type icons, brand and bank logos, Azure service icons, and design-system sets. The browse catalog now lists 566,800 icons across 420 sets.",
		added: [
			"Added Azure Icon Collection (1,114 icons).",
			"Added Badgen Icons (82 icons).",
			"Added Bank Logos (424 icons).",
			"Added Dripicons (200 icons).",
			"Added Elementor Icons (514 icons).",
			"Added File Icon Vectors in Classic, Vivid, Square O, and High Contrast (1,637 icons).",
			"Added IcoFont (2,095 icons).",
			"Added Icon Brew (310 icons).",
			"Added Instructure UI Icons in Line, Fill, and Custom (859 icons).",
			"Added JTB Icons (1,482 icons).",
			"Added Microns (172 icons).",
			"Added Nataicons (120 icons).",
			"Added Orchid Icons (283 icons).",
			"Added Pe-icon-7-stroke (202 icons).",
			"Added Power BI Icons (95 icons).",
			"Added Raivo Issuer Icons (1,164 icons).",
			"Added Sanity Icons (236 icons).",
			"Added Small-n-flat (169 icons).",
			"Added SVG Loaders (12 icons).",
			"Added Toe Icons (120 icons).",
			"Added VectorLogoZone (1,761 icons).",
			"Added Vitamix by Decathlon (492 icons).",
			"Added Zero Icons (369 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "553k",
		title: "12 more icon families",
		tag: "Icons",
		summary:
			"Vendored 12 open icon families, including desktop themes, map symbols, and weather sets. The browse catalog now lists 552,900 icons across 397 sets.",
		added: [
			"Added Firefox OS Icons (209 icons).",
			"Added Geomicons Open (58 icons).",
			"Added GovIcons (114 icons).",
			"Added Kamon (171 icons).",
			"Added La Capitaine Icon Theme (6,850 icons).",
			"Added Metro UI Icons (967 icons).",
			"Added Olicons in Outline, Fill, Sharp Outline, and Sharp Fill (678 icons).",
			"Added SJJB Map Icons (245 icons).",
			"Added Tango Icon Theme (215 icons).",
			"Added ThemeIsle Icons (100 icons).",
			"Added Weather Underground Icons in Color and Fill (80 icons).",
			"Added Zocial (113 icons).",
		],
	},
	{
		date: "2026-10-02",
		version: "543k",
		title: "120 new icon families",
		tag: "Icons",
		summary:
			"Vendored 120 open icon families that were not already in the library. The browse catalog now lists 543,100 icons across 385 sets.",
		added: [
			"Added 3dicons (8 icons).",
			"Added AWS Icons (1,001 icons).",
			"Added Aegis Icons (1,016 icons).",
			"Added AirQo Icons (1,384 icons).",
			"Added Altrex Icons (1,585 icons).",
			"Added AnimateIcons (1,140 icons).",
			"Added Appstract (590 icons).",
			"Added Arashi Icon Set (262 icons).",
			"Added Astroicons (53 icons).",
			"Added Azure Visio Stencils (1,236 icons).",
			"Added Bancos em SVG (130 icons).",
			"Added Basil Icons (500 icons).",
			"Added Bili Icon Pack (6 icons).",
			"Added Blobmoji (4,155 icons).",
			"Added Bootstrap Italia Icons (190 icons).",
			"Added Brightlayer UI Icons (4,754 icons).",
			"Added Buckaroo Payment Media (156 icons).",
			"Added Calcite UI Icons (3,504 icons).",
			"Added Catmoji (98 icons).",
			"Added Climacons (33 icons).",
			"Added Counter-Strike Icons (1,537 icons).",
			"Added Country Flags (255 icons).",
			"Added CryptoFont (88 icons).",
			"Added Cryptocoins (330 icons).",
			"Added Developer Icons (334 icons).",
			"Added Disarto Icons (1,504 icons).",
			"Added Discord Badge Vault (2 icons).",
			"Added Doodle Icons (439 icons).",
			"Added Duma Icons (451 icons).",
			"Added Duo Blazor Icons (91 icons).",
			"Added Emblemicons (1,064 icons).",
			"Added Erxes Icons (754 icons).",
			"Added Eyecons (460 icons).",
			"Added FamFamFam Silk (997 icons).",
			"Added File Icons (931 icons).",
			"Added Finmarks (304 icons).",
			"Added Flow Icons (8,100 icons).",
			"Added Forge Icon (568 icons).",
			"Added Frost Icon Theme (277 icons).",
			"Added Game Icon Pack (815 icons).",
			"Added Get It On Badges (13 icons).",
			"Added Global Bank Logos (93 icons).",
			"Added HA Akentner Icons (1 icon).",
			"Added HA Cupertino Icons (595 icons).",
			"Added HA Energy Node Icons (20 icons).",
			"Added HD Icons (603 icons).",
			"Added HV UI Kit Icons (521 icons).",
			"Added HashiCorp Flight (1,352 icons).",
			"Added Helldivers 2 Stratagems (109 icons).",
			"Added Hyperliquid Coin SVGs (223 icons).",
			"Added Iconoteka (14,970 icons).",
			"Added Iconsans (664 icons).",
			"Added Iconspeck (672 icons).",
			"Added Icoziv (1,746 icons).",
			"Added Idea Icon Pack (71 icons).",
			"Added Illustration Foundry (784 icons).",
			"Added Jedd Icons (383 icons).",
			"Added JetBrains Icons (767 icons).",
			"Added JustVector Icons (151 icons).",
			"Added KDesign Icons (2,017 icons).",
			"Added Kendo SVG Icons (2,481 icons).",
			"Added Kivex (309 icons).",
			"Added Koobiq Icons (1,088 icons).",
			"Added Lawnicons (10,171 icons).",
			"Added LibreICONS (2,439 icons).",
			"Added Line MD (1,222 icons).",
			"Added Linea Iconset (1,431 icons).",
			"Added Linearicons (170 icons).",
			"Added LivelyIcons (1,319 icons).",
			"Added Lovelace Weather Icons (15 icons).",
			"Added MOBAIcons (475 icons).",
			"Added MS Emoji (7,906 icons).",
			"Added MSR Icons (2,137 icons).",
			"Added Material OS Icon Pack (31 icons).",
			"Added Monster Hunter Icons (353 icons).",
			"Added MorphNext (2 icons).",
			"Added Moving Icons (549 icons).",
			"Added NSW Design System Icons (15 icons).",
			"Added Neu Icons (1,508 icons).",
			"Added Next Icons (353 icons).",
			"Added Ontario Design System Icons (137 icons).",
			"Added OpenTiny Icons (709 icons).",
			"Added Oracle Font APEX (2,320 icons).",
			"Added Orange Icons (750 icons).",
			"Added Orangeclock Icons (15 icons).",
			"Added Orbit Icons (358 icons).",
			"Added Papirus Icons (2,219 icons).",
			"Added Payment Methods SVG (35 icons).",
			"Added PaymentFont (116 icons).",
			"Added Pixel Vault (69 icons).",
			"Added ProXIcons (1,634 icons).",
			"Added Proxy App Icon Set (83 icons).",
			"Added PureIconPack (morirain) (15 icons).",
			"Added Quill Icons (1 icon).",
			"Added React Crypto Icons (1,200 icons).",
			"Added React Pay Icons (596 icons).",
			"Added React Suite Icons (277 icons).",
			"Added Rpg Awesome (495 icons).",
			"Added Rune Icons (2,895 icons).",
			"Added SWM Icon Pack (894 icons).",
			"Added Samsung One UI Icons (883 icons).",
			"Added Semantic UI Icons (2,228 icons).",
			"Added ShopIcons (996 icons).",
			"Added Sketch Icons (671 icons).",
			"Added Sketchybar App Font (674 icons).",
			"Added Slate Free SVG Icons (10 icons).",
			"Added Suomi.fi Icons (242 icons).",
			"Added Tech Stack Icon (1,386 icons).",
			"Added Terrane (972 icons).",
			"Added TinyGlyphs (250 icons).",
			"Added Twilio Paste Icons (338 icons).",
			"Added Uber Base Web Icons (33 icons).",
			"Added VK Icons (3,531 icons).",
			"Added VS Code Iconset (114 icons).",
			"Added VS Code Material Icon Theme (910 icons).",
			"Added Vigil Icons (111 icons).",
			"Added doo-iconik (595 icons).",
			"Added selfh.st Icons (7,273 icons).",
			"Added taurbalaur SVG Icons (15 icons).",
			"Added vscode-icons (1,665 icons).",
		],
	},
	{
		date: "2026-08-18",
		version: "morph",
		title: "Icon morph playground",
		tag: "Product",
		summary:
			"Stroke icons can now morph into each other in the inspector, powered by [morphicons](https://www.morphicons.com/). Optimal rotation is solved in closed form; springs stay interruptible.",
		added: [
			"Added a Morph tab beside Static: pick two or more line icons, play the sequence, and scrub the interpolation.",
			"Added drag-to-reorder on the morph sequence, plus copy/export for React, Vue, Svelte, React Native, HTML, and vanilla.",
			"Added morph compatibility — path structure, geometry, stroke, and interpolation.",
		],
	},
	{
		date: "2026-08-13",
		version: "dual-era",
		title: "Cursor MCP compatibility",
		tag: "MCP",
		summary:
			"The remote MCP endpoint now speaks both the stateless `2026-07-28` protocol and the handshake-based protocol Cursor still uses. No session stickiness — `initialize` is answered in-request and then forgotten.",
		added: [
			"Added dual-era Streamable HTTP: Cursor `initialize` / `tools/list` / `tools/call` work without the new MCP headers.",
			"Added `ping` and `notifications/initialized` handling for handshake clients.",
			"Kept `server/discover` and per-request `_meta` validation for `2026-07-28` clients.",
		],
	},
	{
		date: "2026-08-09",
		version: "2026-07-28",
		title: "Stateless MCP architecture",
		tag: "MCP",
		summary:
			"Migrated the remote MCP server to protocol `2026-07-28`. Every request is now self-contained — no sessions, no handshake, ready for serverless deployment.",
		removed: [
			"Removed the `initialize` / `initialized` handshake in favor of per-request metadata.",
			"Removed `Mcp-Session-Id` and all session stickiness from the Streamable HTTP transport.",
			"Removed the GET SSE stream endpoint (deprecated HTTP+SSE transport).",
			"Removed the `@modelcontextprotocol/sdk` dependency and duplicated handler code.",
			"Dropped support for legacy protocol version `2024-11-05`.",
		],
		added: [
			"Added `server/discover` to advertise supported versions, capabilities, and server identity.",
			"Added per-request validation of `params._meta.io.modelcontextprotocol/protocolVersion`.",
			"Added required HTTP headers: `MCP-Protocol-Version`, `Mcp-Method`, and `Mcp-Name`.",
			"Added `resultType: \"complete\"` on all JSON-RPC results.",
			"Added `io.modelcontextprotocol/serverInfo` in `_meta` on every response.",
			"Added cache hints (`ttlMs` + `cacheScope: \"public\"`) on discover, list, and read operations.",
			"Added spec error codes `-32020` (HeaderMismatch), `-32022` (UnsupportedProtocolVersion), and `-32601` (Method not found).",
		],
	},
	{
		date: "2025-12-13",
		version: "2024-11-05",
		title: "Initial MCP server",
		tag: "MCP",
		summary:
			"Shipped the first remote MCP endpoint for Aria Icons with tools and resources over Streamable HTTP using the legacy session-based protocol.",
		added: [
			"Added `POST /api/mcp` as a JSON-RPC endpoint for remote MCP clients.",
			"Added the `initialize` / `initialized` session handshake.",
			"Added tools: `list_icons` and `get_icon_svg`.",
			"Added resources for each icon set and a combined `all` resource.",
			"Added the MCP connect dialog in the UI.",
		],
	},
];
